package Task2;
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... .
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
 */
public class Task2 {
    public static void main(String[] args) {
        int sum = 0;
        int next_el;
        int el1 = 1;
        int el2 = 2;
        while (sum < 4000000)
        {
            next_el = el1+el2;
            el1 = el2;
            if (el2 % 2 == 0) sum += el2;
            el2 = next_el;
        }
        System.out.println(sum);
    }
}

