package Task44;
/*
Pentagonal numbers are generated by the formula, P_n=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal and D = |P_k - P_j| is minimised; what is the value of D?
 */
import java.util.ArrayList;

public class Task44 {
    public static void main(String[] args)
    {
        int sum = 0;
        int subtraction = 0;
        int answer = 0;
        ArrayList<Integer> list = new ArrayList<>();
        for(int i=1;i<2500;i++)
        {
            list.add((i*(3*i-1))/2);
        }
            for(int i=1; i < list.size(); i++)
            {
                for(int j=list.size()-1;j>0;j--)
                {
                    if(i==j) continue;
                    sum = list.get(i) + list.get(j);
                    if(!list.contains(sum)) continue;
                    subtraction = list.get(j) - list.get(i);
                    if(!list.contains(subtraction)) continue;
                    answer = subtraction;
                    break;

                }
                if(list.contains(sum) && list.contains(subtraction)) break;
            }
        System.out.println(answer);

        }
    }


